services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: evolution_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_data/postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - n8n_evoapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: ${REDIS_IMAGE}
    container_name: evolution_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - n8n_evoapi

  evolution-api:
    container_name: evolution_api
    image: ${EVO_IMAGE}
    restart: always
    ports:
      - "${EVO_PORT}:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.evolution.rule=Host(`${EVO_DOMAIN}`)
      - traefik.http.routers.evolution.entrypoints=web,websecure
      - traefik.http.routers.evolution.tls=true
      - traefik.http.routers.evolution.tls.certresolver=mytlschallenge
      - traefik.http.routers.evolution.middlewares=evolution-headers@docker
      - traefik.http.middlewares.evolution-headers.headers.SSLRedirect=true
     # - traefik.http.middlewares.evolution-headers.headers.STSSeconds=315360000
    env_file:
      - .env
    environment:
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      DATABASE_CONNECTION_URI: ${DATABASE_CONNECTION_URI}
      CACHE_REDIS_URI: ${CACHE_REDIS_URI}
      SESSION_MODE: ${SESSION_MODE}
      WEBSOCKET_ENABLED: "true"
      WEBSOCKET_GLOBAL_EVENTS: "true"
      WEBSOCKET_IGNORE_ALL_SSL: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - n8n_evoapi

networks:
  n8n_evoapi:
    external: true

volumes:
   postgres_data:
   evolution_instances:
