services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    restart: always
    env_file:
      - .env
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.mytlschallenge.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - n8n_evoapi

  n8n:
    image: ${N8N_IMAGE}
    restart: always
    ports:
      - "127.0.0.1:${N8N_PORT}:${N8N_PORT}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.n8n.entrypoints=web
    extra_hosts:
      - "host.docker.internal:${LOCAL_IP}"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=${NODE_ENV}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_METRICS=${N8N_METRICS}
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_METRICS_INCLUDE_QUEUE_METRICS=${N8N_METRICS_INCLUDE_QUEUE_METRICS}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8n_evoapi

networks:
  n8n_evoapi:
    external: true
